-- Databricks notebook source
CREATE DATABASE IF NOT EXISTS TEST_DEMO_BRONZE;

-- COMMAND ----------

CREATE DATABASE IF NOT EXISTS TEST_DEMO_SILVER;

-- COMMAND ----------

CREATE DATABASE IF NOT EXISTS TEST_DEMO_GOLD;

-- COMMAND ----------


